[Feat] Page CRUD
fing9/whoami pull request #7
Opened 2024-08-10 15:41 UTC by sungpaks

Page 관련 api는 `/api/v1/page` 로 했습니다
- post `/create`로 페이지 생성 : request body로 `userId, title`을 받아요
- get `/{id}`로 특정 페이지 조회
- put `/{id}`로 특정 페이지 수정. request body로 `userId, title`을 받아요
- delete `/{id}`로 특정 페이지 삭제.
- get `/all`로 모든 페이지 조회

`User`엔티티는 `BaseTimeEntity`상속으로 생성/수정시간 넣었고
- `id`는 `IDENTITY`로 자동생성
- `userId`는 String(고유한 유저 값)
- `title`은 String

api들은 swagger-ui에서 요청 확인해볼 수 있게 했고, 테스트해봤습니다.  
security filter는 아직 안 넣었어요. 테스트하느라

2024-08-11 09:14 UTC, fing9 requested changes
리뷰 했으니 확인해주세요

2024-08-11 09:14 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +	public ResponseEntity<?> updatePage(@PathVariable Long id, @RequestBody PageRequestDto pageRequest) {
API 호출한 사람이 페이지의 소유주가 맞는지 확인하는 검증 과정이 필요할 듯 합니다

2024-08-11 09:14 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +	public ResponseEntity<?> deletePage(@PathVariable Long id) {
API 호출한 사람이 페이지의 소유주가 맞는지 확인하는 검증 과정이 필요할 듯 합니다 (2)

2024-08-11 09:14 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +	public ResponseEntity<?> createPage(@RequestBody PageRequestDto pageRequest) {
`@Valid` 어노테이션으로 Dto 객체에 대한 검증을 실시함을 명시해주면 더 좋을 듯 합니다

2024-08-11 09:14 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/domain/entity/Page.java
> +	private String userId;
유저 엔티티를 연관관계 엔티티로 담지 않고 Id만 담게 설계한 이유가 있을까요?

2024-08-11 09:14 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/application/service/UpdatePageService.java
> +	public void updatePage(Long id, PageRequestDto pageDetails) {
존재하는 페이지인지에 대한 유효성 검증이 필요해보입니다. 
지금의 로직대로면 없는 id에 대한 수정 요청이라면 생성을 해버리는데 이게 의도한 동작인지 생각해볼 필요성이 있어보임.

2024-08-11 09:14 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/application/service/GetPageService.java
> +public class GetPageService implements GetPageUseCase {
만들기는 잘 만들었는데 다른 Service에서 적극적으로 이 서비스를 호출해서 사용할 필요가 있어보입니다.

== 사용처가 적음

2024-08-11 09:14 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/application/service/CreatePageService.java
> +	public Page createPage(String userId, String title) {
1. 존재하는 userId인지에대한 검증이 이 서비스에 들어오기 전에 이루어져야 할 것 같네요
2. Page.of에 Id를 빼면 null로 생성된다는게 너무 모호한..? 느낌이 듭니다. 차라리 of 정적 팩토리 생성자는 하나로 퉁치고 외부에서 id위치에 null을 넣어주는 방식으로 하는게 어떨까요 (이건 의견)

2024-08-11 09:14 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/application/service/DeletePageService.java
> +public class DeletePageService implements DeletePageUseCase {
LGTM

2024-08-11 09:14 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/domain/entity/Page.java
> +	@Column
타이틀 길이에 대한 설정을 명시해주는게 좋을 듯 싶네요!!

2024-08-11 11:04 UTC, sungpaks commented on .gitignore
아차? 그 때 물어보기 전에 했던 실수. 뺄게요~

2024-08-11 11:07 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +	private final DeletePageService deletePageService;
어라 그러네요 .. 고치겠으니다

2024-08-11 15:16 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +	public ResponseEntity<?> createPage(@RequestBody PageRequestDto pageRequest) {
추가완료했습니다

2024-08-11 15:16 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +	public ResponseEntity<?> updatePage(@PathVariable Long id, @RequestBody PageRequestDto pageRequest) {
반영하겠읍니다

2024-08-11 15:26 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/domain/entity/Page.java
> +	private String userId;
음.. 별로 없습니다. 일대다매핑 넣어놓을게요~!

2024-08-12 06:21 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/application/service/GetPageService.java
> +public class GetPageService implements GetPageUseCase {
사용처를 고려해보겠습니다

2024-08-12 06:26 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/domain/entity/Page.java
> +	@Column
100으로 했습니다 일단~

2024-08-12 06:27 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/application/service/UpdatePageService.java
> +	public void updatePage(Long id, PageRequestDto pageDetails) {
확실히 그렇네요. 검증 추가했습니다

2024-08-12 06:29 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/application/service/CreatePageService.java
> +	public Page createPage(String userId, String title) {
1. 말씀하시는 검증이 "userId가 존재하지 않을까봐"이면, 이제 `@AuthenticationPrincipal`로 가져오니 괜찮지 않나 싶고, "이미 있는 userId인데 또 생성함?"이면, 유저가 여러 페이지를 생성할 수 있으니 문제없어보입니다
2. 정적 팩토리 생성자는 하나만 하고, 새로 생성할 때처럼 id가 없는 경우 null로 넣게 했습니다

2024-08-12 07:07 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +		List<GetPageResponseDto> allPages = getPageUseCase.getAllPages().stream().map((page)-> GetPageResponseDto.of(page)).toList();
불변객체로 반환하는거 좋네요~

2024-08-12 07:16 UTC, fing9 requested changes
전체적으로 괜찮은데 N+1 문제가 2개 API EndPoint에서 발생하네요. 이거 수정해주세요

2024-08-12 07:16 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +		/*if (userId == null) {
이건 FilterChain에서 거르려고 지우신거 맞나요?

2024-08-12 07:16 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +		if (!getPageUseCase.isOwnerOfPage(id, userId)) {
이런 경우는 Validator Class를 하나 더 만드는 식으로 가는건 어떨까 싶네요!
일단은 이렇게 가고 추후에 검증 로직 추가시에는 분리 생각해보시죠

2024-08-12 07:16 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/in/dto/GetPageResponseDto.java
> +public class GetPageResponseDto {
ResponseDto는 더 편하게 써도 괜찮지 않나 싶은 생각이긴한데 좋아요

2024-08-12 07:16 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/in/dto/GetPageResponseDto.java
> +				page.getUser().getId()
(3) 이 시점에 `GetUser()` 호출 시에 추가 쿼리 발생

2024-08-12 07:16 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +		List<GetPageResponseDto> allPages = getPageUseCase.getAllPages().stream().map((page)-> GetPageResponseDto.of(page)).toList();
그런데 이 시점에서 N+1문제 발생하네요
(2) 이 시점에 `map((page)-> GetPageResponseDto.of(page))` 호출 시에 내부에서 추가 쿼리 발생

2024-08-12 07:16 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/out/PageQueryAdapter.java
> +		return pageRepository.findAll();
(1) findAll 시에 모든 Page의 User객체가 LazyLoading으로 인해 Proxy객체로 채워짐

2024-08-12 07:16 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +		List<GetPageResponseDto> pagesOfUser = getPageUseCase.getPagesOfUser(userId).stream().map((page)-> GetPageResponseDto.of(page)).toList();
N+1문제 위와 동일

2024-08-12 07:16 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/infrastructure/repository/PageRepository.java
> +public interface PageRepository extends JpaRepository<Page, Long> {
여기서 JPQL로 FetchJoin해서 가져오는 코드 추가해서 N+1 문제 해결 해주세요

2024-08-12 07:21 UTC, fing9 commented
N + 1 문제만 해결하면 이제 머지해도 괜찮을 것 같습니다~!

2024-08-13 11:06 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +		/*if (userId == null) {
그것도 있고, 비인증상태면 `anonymousUser`였나? 다른 문자열이 들어오기에 여기보다는 필터체인같은데서 거르는게 좋겠다 싶었습니다

2024-08-13 11:06 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/adapter/in/dto/GetPageResponseDto.java
> +public class GetPageResponseDto {
칠린칠린~

2024-08-13 11:20 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +		if (!getPageUseCase.isOwnerOfPage(id, userId)) {
오 . 좋습니다~

2024-08-13 13:38 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +		List<GetPageResponseDto> pagesOfUser = getPageUseCase.getPagesOfUser(userId).stream().map((page)-> GetPageResponseDto.of(page)).toList();
fetch join 작성해서 사용하게 해봤습니다

2024-08-13 13:39 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/adapter/out/PageQueryAdapter.java
> +		return pageRepository.findAll();
EAGER로딩으로 바꿔봤습니당

2024-08-13 13:40 UTC, sungpaks commented on src/main/java/com/dahhong/whoami/page/adapter/in/dto/GetPageResponseDto.java
> +				page.getUser().getId()
(2) 이 시점에 map((page)-> GetPageResponseDto.of(page)) 호출 시에 내부에서 추가 쿼리 발생
여기에서 말하는 *내부에서 발생하는 추가 쿼리*가 (3) `Getuser()`호출 시 추가 쿼리 발생 인건가요?

2024-08-21 07:17 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/out/PageQueryAdapter.java
> +		return pageRepository.findAll();
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ JPQL로 하는게 좋지 않을까..? 싶긴한데 일단 그렇게 지나가시죠

2024-08-21 07:17 UTC, fing9 commented on src/main/java/com/dahhong/whoami/page/adapter/out/PageQueryAdapter.java
> +		return pageRepository.findAll();
추후에 한 번에 바꾸는걸로

2024-08-21 07:17 UTC, fing9 approved these changes
머지하시죠!!

2024-08-21 07:18 UTC, merged

2024-08-21 07:42 UTC, joojae02 commented on src/main/java/com/dahhong/whoami/page/adapter/in/PageController.java
> +	public ResponseEntity<?> deletePage(@PathVariable Long id) {
싫어요.

2024-08-21 08:25 UTC, joojae02 commented
@fing9 @sungpaks 
왜 코멘트 지우시죠
이거 언론 탄압입니다.

2024-08-21 08:43 UTC, joojae02 commented
> @fing9 @sungpaks 잘못 작성한 코멘트를 지워주신 점에 대해서 감사합니다.
> 
> * 음음.. 확실히 제가 영양가 없는 코멘트 달긴 했죠. 이거 언론 통제라고 생각하는 사람도 있곘지만 저는 인정합니다.

![image](https://github.com/user-attachments/assets/bb881b10-621d-41c6-8dd5-bd477c5aa4ec)
딱걸렸어. 이사람아.